"""add_target_price_to_product

Revision ID: 11b32272c9cf
Revises: 16f365da7476
Create Date: 2026-07-26 14:24:27.138543
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b32272c9cf'
down_revision: Union[str, Sequence[str], None] = '16f365da7476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
