"""add_target_price_to_product

Revision ID: 16f365da7476
Revises: 6107b73496ec
Create Date: 2026-07-26 14:06:19.560228
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f365da7476'
down_revision: Union[str, Sequence[str], None] = '6107b73496ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'target_price')
    # ### end Alembic commands ###
