"""add catalog and users tables

Revision ID: 3b0ab9a0a29d
Revises: f1265267888f
Create Date: 2026-07-14 18:34:52.163994
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b0ab9a0a29d'
down_revision: Union[str, Sequence[str], None] = 'f1265267888f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
