"""add_category_entity

Revision ID: 6107b73496ec
Revises: 8edd16b8c970
Create Date: 2026-07-22 21:49:22.364990
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6107b73496ec'
down_revision: Union[str, Sequence[str], None] = '8edd16b8c970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
